-- Extensions and the Spring AI vector store table.
-- Flyway owns ALL DDL: spring.ai.vectorstore.pgvector.initialize-schema stays false,
-- so the applied schema is deterministic and versioned.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE vector_store (
    id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    content   text NOT NULL,
    metadata  jsonb,
    embedding vector(${vector_dimension})
);

-- ANN index for cosine similarity search.
CREATE INDEX idx_vector_store_embedding ON vector_store
    USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- Serves the jsonpath (metadata::jsonb @@ ...) predicates generated by
-- PgVectorFilterExpressionConverter for user/document scoping on the vector leg.
CREATE INDEX idx_vector_store_metadata ON vector_store USING gin (metadata jsonb_path_ops);

-- Serve the SQL-side scoping used by the full-text leg.
CREATE INDEX idx_vector_store_user ON vector_store ((metadata->>'user_id'));
CREATE INDEX idx_vector_store_document ON vector_store ((metadata->>'document_id'));
